name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # サブモジュールを再帰的に取得
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make zip
      
    - name: Build and run tests
      run: |
        cd c
        make
        ./test_cstruct
        
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update library.properties version
      run: |
        sed -i "s/^version=.*/version=${{ steps.get_version.outputs.VERSION }}/" arduino/library.properties

    - name: Create package
      run: |
        ./scripts/create_package.sh ${{ steps.get_version.outputs.VERSION }}
        
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: cstruct-arduino-${{ steps.get_version.outputs.VERSION }}
        path: dist/cstruct-arduino-${{ steps.get_version.outputs.VERSION }}.zip
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/cstruct-arduino-${{ steps.get_version.outputs.VERSION }}.zip
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
