name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # サブモジュールを再帰的に取得
      
    - name: Cache Arduino directories
      uses: actions/cache@v3
      with:
        path: |
          _arduino-data
          _arduino-downloads
          _arduino-user
        key: ${{ runner.os }}-arduino-${{ hashFiles('scripts/test_arduino.sh') }}
        restore-keys: |
          ${{ runner.os }}-arduino-
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
    - name: Arduino Lint
      uses: arduino/arduino-lint-action@v1
      with:
        library-manager: false
        compliance: specification
        path: ./arduino
        verbose: false

    - name: Build and run tests
      run: |
        cd c
        make
        ./test_cstruct
        cd ../
        ./scripts/test_arduino.sh
