name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # サブモジュールを再帰的に取得
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
    - name: Build and run tests
      run: |
        cd c
        make
        ./test_cstruct
        cd ../
        ./scripts/test_arduino.sh

